version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      - config set slave-read-only no
    ports:
      - 6379:6379

  mysql:
    build: ./
    container_name: mysql
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    command:
      - --authentication_policy=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
      - ./disk:/disk
    ports:
      - 33061:3306
    restart: always
